# fly.toml app configuration file generated for strive-planner on 2024-12-28T15:43:07-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'strive-planner'
primary_region = 'sea'
kill_signal = 'SIGTERM'

[build]

[deploy]

[env]
  PHX_HOST = 'strive-planner.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
